

from __future__ import annotations

from .actor import Actor as Actor
from .event import Event as Event
from .status import Status as Status
from .classroom import Classroom as Classroom
from .enterprise import Enterprise as Enterprise
from .rate_limit import RateLimit as RateLimit
from .gist_simple import GistSimple as GistSimple
from .integration import Integration as Integration
from .public_user import PublicUser as PublicUser
from .organization import Organization as Organization
from .private_user import PrivateUser as PrivateUser
from .cvss_severity import CvssSeverity as CvssSeverity
from .link_with_type import LinkWithType as LinkWithType
from .code_of_conduct import CodeOfConduct as CodeOfConduct
from .global_advisory import GlobalAdvisory as GlobalAdvisory
from .gist_list_params import GistListParams as GistListParams
from .simple_classroom import SimpleClassroom as SimpleClassroom
from .user_list_params import UserListParams as UserListParams
from .event_list_params import EventListParams as EventListParams
from .issue_list_params import IssueListParams as IssueListParams
from .nullable_git_user import NullableGitUser as NullableGitUser
from .org_update_params import OrgUpdateParams as OrgUpdateParams
from .organization_full import OrganizationFull as OrganizationFull
from .feed_list_response import FeedListResponse as FeedListResponse
from .gist_create_params import GistCreateParams as GistCreateParams
from .gist_list_response import GistListResponse as GistListResponse
from .gist_update_params import GistUpdateParams as GistUpdateParams
from .minimal_repository import MinimalRepository as MinimalRepository
from .repo_update_params import RepoUpdateParams as RepoUpdateParams
from .team_update_params import TeamUpdateParams as TeamUpdateParams
from .user_list_response import UserListResponse as UserListResponse
from .user_update_params import UserUpdateParams as UserUpdateParams
from .emoji_list_response import EmojiListResponse as EmojiListResponse
from .event_list_response import EventListResponse as EventListResponse
from .issue_list_response import IssueListResponse as IssueListResponse
from .license_list_params import LicenseListParams as LicenseListParams
from .advisory_list_params import AdvisoryListParams as AdvisoryListParams
from .marketplace_purchase import MarketplacePurchase as MarketplacePurchase
from .repo_transfer_params import RepoTransferParams as RepoTransferParams
from .classroom_list_params import ClassroomListParams as ClassroomListParams
from .license_list_response import LicenseListResponse as LicenseListResponse
from .project_update_params import ProjectUpdateParams as ProjectUpdateParams
from .zen_retrieve_response import ZenRetrieveResponse as ZenRetrieveResponse
from .advisory_list_response import AdvisoryListResponse as AdvisoryListResponse
from .markdown_render_params import MarkdownRenderParams as MarkdownRenderParams
from .meta_retrieve_response import MetaRetrieveResponse as MetaRetrieveResponse
from .org_list_events_params import OrgListEventsParams as OrgListEventsParams
from .org_list_issues_params import OrgListIssuesParams as OrgListIssuesParams
from .repo_list_teams_params import RepoListTeamsParams as RepoListTeamsParams
from .repository_list_params import RepositoryListParams as RepositoryListParams
from .user_list_gists_params import UserListGistsParams as UserListGistsParams
from .user_list_teams_params import UserListTeamsParams as UserListTeamsParams
from .classroom_list_response import ClassroomListResponse as ClassroomListResponse
from .get_root_links_response import GetRootLinksResponse as GetRootLinksResponse
from .gist_list_public_params import GistListPublicParams as GistListPublicParams
from .octocat_retrieve_params import OctocatRetrieveParams as OctocatRetrieveParams
from .repo_get_license_params import RepoGetLicenseParams as RepoGetLicenseParams
from .repo_list_events_params import RepoListEventsParams as RepoListEventsParams
from .user_list_issues_params import UserListIssuesParams as UserListIssuesParams
from .gist_list_commits_params import GistListCommitsParams as GistListCommitsParams
from .gist_list_starred_params import GistListStarredParams as GistListStarredParams
from .markdown_render_response import MarkdownRenderResponse as MarkdownRenderResponse
from .notification_list_params import NotificationListParams as NotificationListParams
from .org_list_events_response import OrgListEventsResponse as OrgListEventsResponse
from .org_list_issues_response import OrgListIssuesResponse as OrgListIssuesResponse
from .organization_list_params import OrganizationListParams as OrganizationListParams
from .repo_list_teams_response import RepoListTeamsResponse as RepoListTeamsResponse
from .repo_merge_branch_params import RepoMergeBranchParams as RepoMergeBranchParams
from .repository_list_response import RepositoryListResponse as RepositoryListResponse
from .search_result_text_match import SearchResultTextMatch as SearchResultTextMatch
from .user_list_gists_response import UserListGistsResponse as UserListGistsResponse
from .user_list_teams_response import UserListTeamsResponse as UserListTeamsResponse
from .user_retrieve_0_response import UserRetrieve0Response as UserRetrieve0Response
from .user_retrieve_1_response import UserRetrieve1Response as UserRetrieve1Response
from .gist_list_public_response import GistListPublicResponse as GistListPublicResponse
from .license_retrieve_response import LicenseRetrieveResponse as LicenseRetrieveResponse
from .repo_get_license_response import RepoGetLicenseResponse as RepoGetLicenseResponse
from .repo_list_activity_params import RepoListActivityParams as RepoListActivityParams
from .repo_list_events_response import RepoListEventsResponse as RepoListEventsResponse
from .repo_list_watchers_params import RepoListWatchersParams as RepoListWatchersParams
from .user_list_gpg_keys_params import UserListGpgKeysParams as UserListGpgKeysParams
from .user_list_issues_response import UserListIssuesResponse as UserListIssuesResponse
from .user_list_projects_params import UserListProjectsParams as UserListProjectsParams
from .gist_list_commits_response import GistListCommitsResponse as GistListCommitsResponse
from .gist_list_starred_response import GistListStarredResponse as GistListStarredResponse
from .markdown_render_raw_params import MarkdownRenderRawParams as MarkdownRenderRawParams
from .network_list_events_params import NetworkListEventsParams as NetworkListEventsParams
from .notification_list_response import NotificationListResponse as NotificationListResponse
from .organization_list_response import OrganizationListResponse as OrganizationListResponse
from .user_create_project_params import UserCreateProjectParams as UserCreateProjectParams
from .repo_compare_commits_params import RepoCompareCommitsParams as RepoCompareCommitsParams
from .repo_list_activity_response import RepoListActivityResponse as RepoListActivityResponse
from .repo_list_stargazers_params import RepoListStargazersParams as RepoListStargazersParams
from .repo_list_watchers_response import RepoListWatchersResponse as RepoListWatchersResponse
from .security_advisory_ecosystem import SecurityAdvisoryEcosystem as SecurityAdvisoryEcosystem
from .security_advisory_epp_score import SecurityAdvisoryEppScore as SecurityAdvisoryEppScore
from .simple_classroom_assignment import SimpleClassroomAssignment as SimpleClassroomAssignment
from .simple_classroom_repository import SimpleClassroomRepository as SimpleClassroomRepository
from .user_list_gpg_keys_response import UserListGpgKeysResponse as UserListGpgKeysResponse
from .user_list_projects_response import UserListProjectsResponse as UserListProjectsResponse
from .assignment_retrieve_response import AssignmentRetrieveResponse as AssignmentRetrieveResponse
from .markdown_render_raw_response import MarkdownRenderRawResponse as MarkdownRenderRawResponse
from .network_list_events_response import NetworkListEventsResponse as NetworkListEventsResponse
from .org_list_attestations_params import OrgListAttestationsParams as OrgListAttestationsParams
from .rate_limit_retrieve_response import RateLimitRetrieveResponse as RateLimitRetrieveResponse
from .repo_list_languages_response import RepoListLanguagesResponse as RepoListLanguagesResponse
from .team_list_child_teams_params import TeamListChildTeamsParams as TeamListChildTeamsParams
from .team_list_invitations_params import TeamListInvitationsParams as TeamListInvitationsParams
from .user_list_followers_0_params import UserListFollowers0Params as UserListFollowers0Params
from .user_list_followers_1_params import UserListFollowers1Params as UserListFollowers1Params
from .user_list_public_keys_params import UserListPublicKeysParams as UserListPublicKeysParams
from .user_retrieve_by_id_response import UserRetrieveByIDResponse as UserRetrieveByIDResponse
from .org_list_installations_params import OrgListInstallationsParams as OrgListInstallationsParams
from .repo_compare_commits_response import RepoCompareCommitsResponse as RepoCompareCommitsResponse
from .repo_list_contributors_params import RepoListContributorsParams as RepoListContributorsParams
from .repo_list_stargazers_response import RepoListStargazersResponse as RepoListStargazersResponse
from .security_advisory_credit_type import SecurityAdvisoryCreditType as SecurityAdvisoryCreditType
from .user_list_attestations_params import UserListAttestationsParams as UserListAttestationsParams
from .user_list_repositories_params import UserListRepositoriesParams as UserListRepositoriesParams
from .codes_of_conduct_list_response import CodesOfConductListResponse as CodesOfConductListResponse
from .org_list_attestations_response import OrgListAttestationsResponse as OrgListAttestationsResponse
from .repo_sync_with_upstream_params import RepoSyncWithUpstreamParams as RepoSyncWithUpstreamParams
from .team_list_child_teams_response import TeamListChildTeamsResponse as TeamListChildTeamsResponse
from .team_list_invitations_response import TeamListInvitationsResponse as TeamListInvitationsResponse
from .user_list_followers_0_response import UserListFollowers0Response as UserListFollowers0Response
from .user_list_followers_1_response import UserListFollowers1Response as UserListFollowers1Response
from .user_list_public_emails_params import UserListPublicEmailsParams as UserListPublicEmailsParams
from .user_list_public_keys_response import UserListPublicKeysResponse as UserListPublicKeysResponse
from .user_retrieve_hovercard_params import UserRetrieveHovercardParams as UserRetrieveHovercardParams
from .assignment_list_accepted_params import AssignmentListAcceptedParams as AssignmentListAcceptedParams
from .org_list_installations_response import OrgListInstallationsResponse as OrgListInstallationsResponse
from .org_set_security_feature_params import OrgSetSecurityFeatureParams as OrgSetSecurityFeatureParams
from .repo_list_contributors_response import RepoListContributorsResponse as RepoListContributorsResponse
from .user_list_attestations_response import UserListAttestationsResponse as UserListAttestationsResponse
from .user_list_repositories_response import UserListRepositoriesResponse as UserListRepositoriesResponse
from .notification_mark_as_read_params import NotificationMarkAsReadParams as NotificationMarkAsReadParams
from .repo_create_commit_status_params import RepoCreateCommitStatusParams as RepoCreateCommitStatusParams
from .repo_create_from_template_params import RepoCreateFromTemplateParams as RepoCreateFromTemplateParams
from .repo_sync_with_upstream_response import RepoSyncWithUpstreamResponse as RepoSyncWithUpstreamResponse
from .user_list_organizations_0_params import UserListOrganizations0Params as UserListOrganizations0Params
from .user_list_organizations_1_params import UserListOrganizations1Params as UserListOrganizations1Params
from .user_list_public_emails_response import UserListPublicEmailsResponse as UserListPublicEmailsResponse
from .user_list_social_accounts_params import UserListSocialAccountsParams as UserListSocialAccountsParams
from .user_list_subscriptions_0_params import UserListSubscriptions0Params as UserListSubscriptions0Params
from .user_list_subscriptions_1_params import UserListSubscriptions1Params as UserListSubscriptions1Params
from .user_retrieve_hovercard_response import UserRetrieveHovercardResponse as UserRetrieveHovercardResponse
from .assignment_list_accepted_response import AssignmentListAcceptedResponse as AssignmentListAcceptedResponse
from .classroom_list_assignments_params import ClassroomListAssignmentsParams as ClassroomListAssignmentsParams
from .repo_create_dispatch_event_params import RepoCreateDispatchEventParams as RepoCreateDispatchEventParams
from .user_list_ssh_signing_keys_params import UserListSSHSigningKeysParams as UserListSSHSigningKeysParams
from .notification_mark_as_read_response import NotificationMarkAsReadResponse as NotificationMarkAsReadResponse
from .org_list_failed_invitations_params import OrgListFailedInvitationsParams as OrgListFailedInvitationsParams
from .user_list_organizations_0_response import UserListOrganizations0Response as UserListOrganizations0Response
from .user_list_organizations_1_response import UserListOrganizations1Response as UserListOrganizations1Response
from .user_list_social_accounts_response import UserListSocialAccountsResponse as UserListSocialAccountsResponse
from .user_list_subscriptions_0_response import UserListSubscriptions0Response as UserListSubscriptions0Response
from .user_list_subscriptions_1_response import UserListSubscriptions1Response as UserListSubscriptions1Response
from .assignment_retrieve_grades_response import AssignmentRetrieveGradesResponse as AssignmentRetrieveGradesResponse
from .classroom_list_assignments_response import ClassroomListAssignmentsResponse as ClassroomListAssignmentsResponse
from .org_list_security_advisories_params import OrgListSecurityAdvisoriesParams as OrgListSecurityAdvisoriesParams
from .user_list_ssh_signing_keys_response import UserListSSHSigningKeysResponse as UserListSSHSigningKeysResponse
from .org_list_failed_invitations_response import OrgListFailedInvitationsResponse as OrgListFailedInvitationsResponse
from .installation_list_repositories_params import (
    InstallationListRepositoriesParams as InstallationListRepositoriesParams,
)
from .org_list_security_advisories_response import (
    OrgListSecurityAdvisoriesResponse as OrgListSecurityAdvisoriesResponse,
)
from .user_list_starred_repositories_params import (
    UserListStarredRepositoriesParams as UserListStarredRepositoriesParams,
)
from .app_manifest_create_conversion_response import (
    AppManifestCreateConversionResponse as AppManifestCreateConversionResponse,
)
from .installation_list_repositories_response import (
    InstallationListRepositoriesResponse as InstallationListRepositoriesResponse,
)
from .user_list_starred_repositories_response import (
    UserListStarredRepositoriesResponse as UserListStarredRepositoriesResponse,
)
from .application_list_installation_requests_params import (
    ApplicationListInstallationRequestsParams as ApplicationListInstallationRequestsParams,
)
from .repo_get_code_security_configuration_response import (
    RepoGetCodeSecurityConfigurationResponse as RepoGetCodeSecurityConfigurationResponse,
)
from .application_list_installation_requests_response import (
    ApplicationListInstallationRequestsResponse as ApplicationListInstallationRequestsResponse,
)
